### ISSUE TITLE
Core, Base Infrastructure

### ISSUE THREAD

**Issue by jcspencer** [FrogMessenger/NewFrog#1]
What is planned to be the core infrastructure behind this project? As stated in the README, it is *not* BitMessage-based.

Does the proposed project it still use messaging nodes, or something like it? If not, what system does it use? Is it peer-to-peer?

I look forward to hearing more about this project!

**Comment by Jaxkr** [comment]
Not exactly sure yet. P2P when directly messaging, but uses servers like email when either party is offline.

I'll have more fleshed out details when I finish it.

**Comment by dave911d** [comment]
would the email be encrypted with something like PGP or would it be a different encryption provider if at all?

**Comment by Jaxkr** [comment]
Everything is encrypted using 2048 bit RSA.

**Comment by dave911d** [comment]
Thanks for answering
